version: '3.6'
services:
  hasura:
    image: hasura/graphql-engine:v2.32.0
    ports:
    - "8080:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgresql://blokprod:xxxxxxxxxxxxxxx@db-scan.explorer.net:5432/bdjuno-mainnet
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      HASURA_GRAPHQL_DATABASE_URL: postgresql://blokprod:xxxxxxxxxxxxxxx@db-scan.explorer.net:5432/bdjuno-mainnet
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: xxxxxxxxxxxxxxxxxxxxxxx
      ACTION_BASE_URL: https://crest.terramirum.com
      # HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"

